## (aichallenge-2024)Pure Pursuit 
/aichallenge/workspace/src/aichallenge_submit/aichallenge_submit_launch/config/control/trajectory_follower/lateral/simple_pure_pursuit.param.yaml:
  ros__parameters:
    external_target_vel:
      min: 7.0
      max: 10.0
      type: float
    lookahead_gain: 
      min: 0.20
      max: 0.80
      type: float
    lookahead_min_distance:
      min: 1.0
      max: 8.0
      type: float
    speed_proportional_gain:
      min: 0.5
      max: 3.0
      type: float
